#include "GMinst.h"

#include "Piano1_samples.h" 
#include "ChurchOrg1_samples.h"
#include "NylonstrGt_samples.h"
#include "Violin_samples.h"
#include "Flute_samples.h"
#include "SpaceVoice_samples.h"
#include "Harpsichord_samples.h"
#include "Glockenspiel_samples.h"
#include "Tubularbell_samples.h"
#include "ChoirAahs_samples.h"
#include "SynthDrum_samples.h"
#include "SteelDrums_samples.h"
#include "Banjo_samples.h"
#include "Bird_samples.h"
#include "BottleBlow_samples.h"
#include "Brightness_samples.h"
#include "Clarinet_samples.h"
#include "EPiano2_samples.h"
#include "EchoDrops_samples.h"
#include "Harp_samples.h"
#include "Honkytonk_samples.h"
#include "Marimba_samples.h"
#include "OrchestraHit_samples.h"
#include "PanFlute_samples.h"
#include "StarTheme_samples.h"
#include "Xylophone_samples.h"
#include "Bandoneon_samples.h"
#include "BaritoneSax_samples.h"
#include "Bassoon_samples.h"
#include "BowedGlass_samples.h"
#include "BreathNoise_samples.h"
#include "Clav_samples.h"
#include "EPiano1_samples.h"
#include "GtHarmonics_samples.h"
#include "Harmonica_samples.h"
#include "Helicopter_samples.h"
#include "Kalimba_samples.h"
#include "MusicBox_samples.h"
#include "PizzicatoStr_samples.h"
#include "ReedOrgan_samples.h"
#include "Santur_samples.h"
#include "Sitar_samples.h"
#include "Taiko_samples.h"
#include "Telephone1_samples.h"
#include "TinkleBell_samples.h"
#include "Whistle_samples.h"
#include "Applause_samples.h"
#include "Contrabass_samples.h"
#include "Crystal_samples.h"
#include "EnglishHorn_samples.h"
#include "Goblin_samples.h"
#include "MeloTom1_samples.h"
#include "Oboe_samples.h"
#include "Organ2_samples.h"
#include "Piccolo_samples.h"
#include "Recorder_samples.h"
#include "ReverseCym_samples.h"
#include "Shamisen_samples.h"
#include "AccordionFr_samples.h"
#include "AltoSax_samples.h"
#include "Cello_samples.h"
#include "ChifferLead_samples.h"
#include "Fiddle_samples.h"
#include "FingeredBs_samples.h"
#include "Koto_samples.h"
#include "MutedGt_samples.h"
#include "Ocarina_samples.h"
#include "Organ3_samples.h"
#include "Shanai_samples.h"
#include "SoloVox_samples.h"
#include "TenorSax_samples.h"
#include "Atmosphere_samples.h"
#include "Bagpipe_samples.h"
#include "Fantasia_samples.h"
#include "IceRain_samples.h"
#include "Seashore_samples.h"
#include "SlapBass2_samples.h"
#include "SynVox_samples.h"
#include "Tuba_samples.h"
#include "Viola_samples.h"
#include "VoiceOohs_samples.h"
#include "5thSawWave_samples.h"
#include "Charang_samples.h"
#include "CleanGt_samples.h"
#include "MutedTrumpet_samples.h"
#include "Trombone_samples.h"
#include "Trumpet_samples.h"
#include "Vibraphone_samples.h"
#include "AcousticBs_samples.h"
#include "Agogo_samples.h"
#include "BassLead_samples.h"
#include "Brass1_samples.h"
#include "Celesta_samples.h"
#include "DistortionGt_samples.h"
#include "FrenchHorns_samples.h"
#include "FretlessBs_samples.h"
#include "HaloPad_samples.h"
#include "JazzGt_samples.h"
#include "MetalPad_samples.h"
#include "Organ1_samples.h"
#include "OverdriveGt_samples.h"
#include "Piano2_samples.h"
#include "Piano3_samples.h"
#include "PickedBs_samples.h"
#include "Polysynth_samples.h"
#include "SawWave_samples.h"
#include "Shakuhachi_samples.h"
#include "SlapBass1_samples.h"
#include "SlowStrings_samples.h"
#include "SopranoSax_samples.h"
#include "Soundtrack_samples.h"
#include "SquareWave_samples.h"
#include "SteelstrGt_samples.h"
#include "Strings_samples.h"
#include "SweepPad_samples.h"
#include "SynCalliope_samples.h"
#include "SynStrings1_samples.h"
#include "SynStrings2_samples.h"
#include "SynthBass1_samples.h"
#include "SynthBass2_samples.h"
#include "SynthBrass1_samples.h"
#include "SynthBrass2_samples.h"
#include "TremoloStr_samples.h"
#include "WarmPad_samples.h"

// the following are some of the 128 instruments in the General MIDI 
// instrument bank
const PROGMEM AudioSynthWavetable::instrument_data * GMinst[] = {
/*000*/ &Piano1,
/*001*/ &Piano2,
/*002*/ &Piano3,
/*003*/ &Honkytonk,
/*004*/ &EPiano1,
/*005*/ &EPiano2,
/*006*/ &Harpsichord,
/*007*/ &Clav,
/*008*/ &Celesta,
/*009*/ &Glockenspiel,
/*010*/ &MusicBox,
/*011*/ &Vibraphone,
/*012*/ &Marimba,
/*013*/ &Xylophone,
/*014*/ &Tubularbell,
/*015*/ &Vibraphone,
/*016*/ &Organ1,
/*017*/ &Organ2,
/*018*/ &Organ3,
/*019*/ &ChurchOrg1,
/*020*/ &ReedOrgan,
/*021*/ &AccordionFr,
/*022*/ &Harmonica,
/*023*/ &Bandoneon,
/*024*/ &NylonstrGt,
/*025*/ &SteelstrGt,
/*026*/ &JazzGt,
/*027*/ &CleanGt,
/*028*/ &MutedGt,
/*029*/ &OverdriveGt,
/*030*/ &DistortionGt,
/*031*/ &GtHarmonics,
/*032*/ &AcousticBs,
/*033*/ &FingeredBs,
/*034*/ &PickedBs,
/*035*/ &FretlessBs,
/*036*/ &SlapBass1,
/*037*/ &SlapBass2,
/*038*/ &SynthBass1,
/*039*/ &SynthBass2,
/*040*/ &Violin,
/*041*/ &Viola,
/*042*/ &Cello,
/*043*/ &Contrabass,
/*044*/ &TremoloStr,
/*045*/ &PizzicatoStr,
/*046*/ &Harp,
/*047*/ &SynthDrum, // should be timpani
/*048*/ &Strings,
/*049*/ &SlowStrings,
/*050*/ &SynStrings1,
/*051*/ &SynStrings2,
/*052*/ &ChoirAahs,
/*053*/ &VoiceOohs,
/*054*/ &SynVox,
/*055*/ &OrchestraHit,
/*056*/ &Trumpet,
/*057*/ &Trombone,
/*058*/ &Tuba,
/*059*/ &MutedTrumpet,
/*060*/ &FrenchHorns,
/*061*/ &Brass1,
/*062*/ &SynthBrass1,
/*063*/ &SynthBrass2,
/*064*/ &SopranoSax,
/*065*/ &AltoSax,
/*066*/ &TenorSax,
/*067*/ &BaritoneSax,
/*068*/ &Oboe,
/*069*/ &EnglishHorn,
/*070*/ &Bassoon,
/*071*/ &Clarinet,
/*072*/ &Piccolo,
/*073*/ &Flute,
/*074*/ &Recorder,
/*075*/ &PanFlute,
/*076*/ &BottleBlow,
/*077*/ &Shakuhachi,
/*078*/ &Whistle,
/*079*/ &Ocarina,
/*080*/ &SquareWave,
/*081*/ &SawWave,
/*082*/ &SynCalliope,
/*083*/ &ChifferLead,
/*084*/ &Charang,
/*085*/ &SoloVox,
/*086*/ &FifthSawWave,
/*087*/ &BassLead,
/*088*/ &Fantasia,
/*089*/ &WarmPad,
/*090*/ &Polysynth,
/*091*/ &SpaceVoice,
/*092*/ &BowedGlass,
/*093*/ &MetalPad,
/*094*/ &HaloPad,
/*095*/ &SweepPad,
/*096*/ &IceRain,
/*097*/ &Soundtrack,
/*098*/ &Crystal,
/*099*/ &Atmosphere,
/*100*/ &Brightness,
/*101*/ &Goblin,
/*102*/ &EchoDrops,
/*103*/ &StarTheme,
/*104*/ &Sitar,
/*105*/ &Banjo,
/*106*/ &Shamisen,
/*107*/ &Koto,
/*108*/ &Kalimba,
/*109*/ &Bagpipe,
/*110*/ &Fiddle,
/*111*/ &Shanai,
/*112*/ &TinkleBell,
/*113*/ &Agogo,
/*114*/ &SteelDrums,
/*115*/ &SynthDrum, // woodblock
/*116*/ &Taiko,
/*117*/ &MeloTom1,
/*118*/ &SynthDrum,
/*119*/ &ReverseCym,
/*120*/ &SynthDrum, // gt fret noise
/*121*/ &BreathNoise,
/*122*/ &Seashore,
/*123*/ &Bird,
/*124*/ &Telephone1,
/*125*/ &Helicopter,
/*126*/ &Applause,
/*127*/ &SynthDrum, // gun shot
};
